# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  api:
    image: webmonitor_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8091:8080
